spring:
  config:
    activate:
      on-profile: test
dima:
  name: test-YAML
  environment: testing
  enabled: false
  servers:
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
  config:
    activate:
      on-profile: prod
dima:
  name: test-YAML
  environment: testing
  enabled: false
  servers:
    - www.abc.test.com
    - www.xyz.test.com

